# FAB14 STAGING database versions
db:
  - version: "2025.6.123456789"
    data: "B"
    dataa: "XX"
    datac: "XX"
    datav: "XX"
  - version: "2025.4.987654321"
    data: "B"
    dataa: "XX"
    datac: "XX"
    datav: "XX"
