version: 1
variables:
  SOURCE_VERSION: "2025.6"
  TARGET_VERSION: "2025.4"
options:
  atomic_write: true
operations:
  - op: copy_item
    path: $.db
    source:
      match: {version: "{{ SOURCE_VERSION }}"}
      expect_matches: 1
    set:
      version: "{{ TARGET_VERSION }}"
    position:
      after:
        match: {version: "{{ SOURCE_VERSION }}"}
        expect_matches: 1
    duplicate:
      unique_by: [version]
      policy: error
